### ISSUE TITLE
Missing data.io dependency

### ISSUE THREAD

**Issue by EvgenyOrekhov** [node-ci/nci#8] opened 2016-02-08 14:47 UTC
After running `git clone https://github.com/node-ci/nci-quick-setup && cd nci-quick-setup && npm install`
and `node_modules/.bin/nci` I get the following error:
```
/nci-quick-setup/node_modules/nci/app.js:255
		if (err) throw err;
		         ^

Error: Cannot find module './node_modules/data.io/lib/server'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/orehov/Downloads/nci-quick-setup/node_modules/nci-classic-ui/dataio.js:4:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
Running `npm install data.io` fixes the problem.

**Comment by okv** [comment] 2016-02-08 18:16
ui already depends on data.io, you can see that [here](https://github.com/node-ci/nci-classic-ui/blob/master/package.json#L40). Tried quick install, it works as expected. Did you have some errors during `npm install`? You can also do `npm ls` after `npm install` to see dependency problems.

**Comment by okv** [comment] 2016-02-08 18:27
Could you try it again? Please check `npm install`, `npm ls` output in case of error.

**Comment by ttyz** [comment] 2016-02-08 20:23
I have the same issue, npm ls shows only these:
UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0
UNMET OPTIONAL DEPENDENCY fsevents@^0.3.1

npm install also show the following: Couldn't install optional dependency: Unsupported 

Besides that, there are no other errors or warnings, but still I get the data.io error on start

**Comment by okv** [comment] 2016-02-09 09:01
That's strange.
Please provide output of the following commands `node --version`, `npm --version`, `npm ls` (attached file, before doing `npm install data.io` manually), your os version (e.g. CentOS 6.6) and architecture (32/64 bit). I'll try to reproduce it. Thanks for your help in resolving this.

**Comment by ttyz** [comment] 2016-02-09 09:54
```
$ node --version
v5.5.0
$ npm --version
3.3.12
```

As for the OS I use a custom distro based on Linux kernel version 4.5.0-rc1+, but I doubt it is os-related

[The output of `npmls`](https://github.com/node-ci/nci/files/122840/npmls.txt)

**Comment by okv** [comment] 2016-02-09 10:53
ok, reproduced and fixed. There was an issue with hacky requiring of data.io parts (server, resources, etc) - it broke with npm 3 because npm 3 installs first level dependencies on one level. I've published updated ui package. Please do quick install again, your current install with manually installing dataio may not work properly. Please also report about results, now quick install should work fine with npm 3.

**Comment by EvgenyOrekhov** [comment] 2016-02-09 13:29
@okv it works now.

**Comment by okv** [comment] 2016-02-09 15:01
@EvgenyOrekhov @ttyz great, thanks for your help

**Closed by okv** 2016-02-09 15:01 UTC
